- package.json
- src/Session.test.ts
- src/Session.ts
This PR adds a keep-alive mechanism that sends an empty comment in set intervals to prevent the connection from timing out.
In addition, it also:
* Removes the `preinstall` script from the root `package.json` as it prevented installing the example projects with `npm` instead of `pnpm`.
> Keep-alive

- README.md
- src/Session.test.ts
- src/Session.ts
Resolves #22 and #21.
This PR adds support for the two most popular EventSource polyfills [`event-source-polyfill`](https://www.npmjs.com/package/event-source-polyfill) and [`eventsource-polyfill`](https://www.npmjs.com/package/eventsource-polyfill), extracting the last event ID from the optional query parameters and sending a 2KB preamble comment when requested by Internet Explorer-based clients.
> Polyfill support

- CHANGELOG.md
- docs/api.md
- src/Session.test.ts
- src/Session.ts
Inspired by [`fastify-sse-v2`](https://github.com/NodeFactoryIo/fastify-sse-v2), this PR adds support for processing iterables and sending yielded values back to the client as events.
In addition, it also renames the `Session#stream` `event` option to `eventName`.
> Generator/Iterator Support

- .gitignore
- CHANGELOG.md
- docs/api.md
- docs/channels.md
- docs/getting-started.md
- docs/recipes.md
- examples/channels/channels/ticker.ts
- examples/getting-started/server.ts
- examples/resource-monitor/channels/resource.ts
- examples/streams/server.ts
- src/Channel.test.ts
- src/Channel.ts
- src/Session.test.ts
- src/Session.ts
This PR re-orders the `Session#push` and `Channel#broadcast` methods to always have the event data first and event name as an optional second argument. In addition, it also allows the user to set a custom event ID as an optional _third_ argument to the `Session#push` method and adds a new `push` event emitted by `Session` after the `Session#push` method is called.
> Re-order session and channel event arguments

- docs/comparison.md
- examples/README.md
- examples/benchmarks/benchmark.ts
- examples/benchmarks/index.ts
- examples/package-lock.json
- examples/package.json
Related to #31.
This PR adds the groundwork for adding a benchmarking suite using [`Benchmark.js`](https://benchmarkjs.com/) and adds a singular simple benchmark comparing pushing an event using channels between `better-sse` and `sse-channel`.
> Benchmarks setup

- docs/api.md
- src/Session.ts
- src/lib/generateId.test.ts
- src/lib/generateId.ts
Resolves #30.
This MR updates the internal event ID generation to use the new [`randomUUID`](https://nodejs.org/api/crypto.html#cryptorandomuuidoptions) Node [`crypto`-library](https://nodejs.org/api/crypto.html) function and falls back to the old method of using [`randomBytes`](https://nodejs.org/api/crypto.html#cryptorandombytessize-callback) if it is not available.
This offers a significant performance boost when using the [`Session#push`](https://github.com/MatthewWid/better-sse/blob/master/docs/api.md#sessionpush-data-unknown-eventname-string-eventid-string--this) and [`Channel#broadcast`](https://github.com/MatthewWid/better-sse/blob/master/docs/api.md#sessionpush-data-unknown-eventname-string-eventid-string--this) methods.
Note that different to #30's recommendations, the event ID …
> Faster random event ID generation

- CHANGELOG.md
- docs/api.md
- src/Channel.test.ts
- src/Channel.ts
This MR improves performance when using channels by implementing the underlying session list with a `Set` instead of an array.
In addition, it updates the `register` and `deregister` methods to short-circuit if the session is already registered or deregistered, respectively and updates the automatic session deregistration to fire the `session-disconnected` event _before_ the event is deregistered instead of _after_.
> Channel performance improvements

- src/Session.test.ts
- src/Session.ts
Resolves #38.
This PR adds the additional response headers `Pragma` and `X-Accel-Buffering` and updates the `Cache-Control` header value, each to disable data transformation, proxy buffering and shared caching to completely disable response data caching.
This ensures that the data sent to the client is unmodified and fresh, as is intended for the correct operation of the event stream mechanism.
> Additional cache response headers

- docs/api.md
- src/Session.test.ts
- src/Session.ts
Resolves #35.
This PR adds a data buffer that buffers written data and only sends it to the client when the `flush` method is called.
In addition, the behaviour of the `dispatch` method has been split into two different methods: `dispatch`, only writing a newline, and `flush` that flushes the buffer data to the client and clears the buffer.
This is a breaking change to the public API and will be released in the next `0.x.0` release.
> Session data buffer

- src/Session.test.ts
- src/Session.ts
This PR updates the Session constructor options `header` field to overwrite conflicting default headers instead of being overwritten by them.
> Session 'headers' option overwrites conflicting default headers

- src/Channel.ts
- src/createChannel.ts
When using different types of sessions, with different `state`s, it's useful to be able to specify the `state` type of sessions inside a channel (instead of overwriting / extending the interface).
This change allows to pass the session state type in addition to the channel state:
```ts
const channel = createChannel<any, { flag: boolean }>();
```
> Allow passing different session "states" per channel

- CHANGELOG.md
- docs/api.md
- package.json
- src/EventBuffer.ts
- src/Session.test.ts
- src/Session.ts
Resolves #42.
This PR adds the ability to batch and send multiple events at once to a session using [event buffers](https://github.com/MatthewWid/better-sse/blob/master/docs/api.md#eventbuffer).
---
Example usage:
```typescript
session.batch((batched) => {
for (let i = 0; i < 100; ++i) {
batched.push(`Event no. ${i}`);
}
});
```
---
Using the exact same helpers as you would with `Session` (`push`, `iterate` and `stream`) you can batch together many events and then send all them in a single transmission.
This is more significantly more performant and uses less network bandwidth overall, and is a necessary precursor to implementing the [event history API](#16).
See [the API documentation](https://github.com/MatthewWid/better-sse/blob/master/docs/api.md#sessionbatch-batcher-eventbuffer--buffe …
> Session event batching

- src/Session.test.ts
- src/Session.ts
Response can also close without request emitting the close event.
both should be listened to set the `isConnected` boolean to false.
Also, pushing data should throw on a disconnected session.
> isConnected should be set on response closed and prevent pushing data

- src/Channel.ts
Was wondering why it's not possible to pass your own eventId using the broadcast function of a channel.
Instead of the generated random UUID you can now pass your own with the use of the options parameter.
> Add option to pass eventId on broadcast

- docs/api.md
- examples/create-keys.ts
- examples/getting-started/pubsub.ts
- src/Channel.test.ts
- src/Channel.ts
- src/Session.test.ts
- src/Session.ts
This PR adds the ability to initialize the value of the `state` property in the `Session` and `Channel` constructor `options` objects.
While enabling the user to construct and set the session/channel state in a single statement, this also allows the TypeScript compiler to automatically infer the state type from the given state value, rather than it having to explicitly defined by passing a type/interface to the `State` generic.
---
Before:
```typescript
interface SessionState {
id: string;
}
const session = await createSession<SessionState>(req, res);
session.state.id = "123";
session.state.id = 456; // Error!
```
After:
```typescript
const session = await createSession(req, res, {
state: {
id: "123"
}
});
session.state.id = 456; // Error!
```
> Allow passing initial session and channel state in constructor

- CHANGELOG.md
- src/createChannel.ts
- src/createSession.ts
This PR fixes an issue where, when creating a session or channel with `createSession` or `createChannel`, if no explicit type is given to the `State` generic it defaults to `unknown` rather than `DefaultSessionState` or `DefaultChannelState`, respectively.
> Fix default state being `unknown` when creating sessions and channels with factories

- examples/benchmarks/benchmark.ts
- examples/benchmarks/lib/createClientPool.ts
- examples/benchmarks/lib/createEventSource.ts
- examples/benchmarks/suites/channel-broadcast.ts
- examples/benchmarks/suites/session-push.ts
- examples/package-lock.json
- examples/package.json
This PR adds a new [performance testing suite](https://benchmarkjs.com/docs/#Suite) to benchmark pushing events to individual clients.
It currently includes benchmarks for `better-sse`, [`sse-channel`](https://www.npmjs.com/package/sse-channel) and [`sse`](https://www.npmjs.com/package/sse).
> Benchmark suite for pushing events to individual clients

- CHANGELOG.md
- docs/src/content/docs/guides/batching.mdx
- docs/src/content/docs/guides/channels.mdx
- docs/src/content/docs/guides/getting-started.mdx
- docs/src/content/docs/index.mdx
- docs/src/content/docs/reference/api.mdx
- docs/src/content/docs/reference/browser-compatibility.mdx
- docs/src/content/docs/reference/comparison.mdx
- docs/src/content/docs/reference/recipes.mdx
- docs/src/content/snippets/home-client.ts
- package.json
- src/Session.ts
- src/createResponse.ts
This PR updates the documentation with the latest changes related to the new support for the Fetch API (#91).
It also adds [Hono](https://hono.dev/)-equivalent examples in each of the code snippets in the guides.
> Fetch API Documentation

- CHANGELOG.md
- README.md
- biome.json
- docs/src/content/docs/guides/getting-started.mdx
- jsr.json
- package.json
- src/EventBuffer.ts
- src/Session.ts
- src/createEventBuffer.ts
- src/lib/createPushFromIterable.ts
- src/lib/createPushFromStream.ts
This PR updates the package to be publishable on the [JavaScript Registry (JSR)](https://jsr.io/), as well as adding explicit return types to a number of methods in the public API to remove [slow types](https://jsr.io/docs/about-slow-types).
> Publish on JSR

- docs/astro.config.ts
- docs/src/content/docs/guides/batching.mdx
- docs/src/content/docs/guides/channels.mdx
- docs/src/content/docs/guides/getting-started.mdx
- docs/src/content/docs/reference/api.mdx
- docs/src/content/docs/reference/comparison.mdx
- docs/src/content/docs/reference/compatibility/browser.mdx
- docs/src/content/docs/reference/compatibility/server.mdx
- docs/src/content/docs/reference/recipes.mdx
This PR adds documentation on the minimum JavaScript version, necessary supported APIs and Node.js version to be able to run Better SSE on a server.
> Add documentation on server compatibility

- docs/src/content/docs/guides/channels.mdx
Fixes the Hono example code for the "Create a channel" docs
> docs: fix import in Hono channels example
